# Generated by Django 4.2.16 on 2024-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_prescription_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
