# Generated by Django 4.2.16 on 2024-10-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_prescription_end_date_prescription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationreminder',
            name='reminder_time',
            field=models.TimeField(),
        ),
    ]
