# Generated by Django 4.2.16 on 2024-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_medication_drugtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('ไม่ระบุ', 'ไม่ระบุ')], max_length=10),
        ),
    ]
