# Generated by Django 4.2.16 on 2024-10-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medication'),
        ),
    ]
